### DISCUSSION TITLE
在ios仓输入法上使用墨奇万象+小鹤双拼·墨奇，如何在iPhone上预设繁体输出？

### DISCUSSION THREAD

**Discussion by yongdalai** [gaboolic/rime-config#177] [Q&A] [answered]
大家好，我是台湾网友，我使用的是墨奇万象+小鹤双拼·墨奇(moqi_wan_flypymo)。
很感谢墨奇的开发者，我目前转移到墨奇输入法觉得有解决很多之前用小鹤双拼的问题。
但我有一个繁体使用者遇到的问题。

在ios仓输入法上面导入墨奇输入法之后，预设都是简体输出。
当然我可以在仓输入法的switcher里选成繁体，但困扰的是聊天时每换一个新视窗、每开一个新网页又回到预设简体输出。
(为了中国网友阅读方便我这篇使用简体，但我身边的台湾友人只用繁体呀。打简体他们会看不懂。)
我好希望在iPhone打字也能跟在电脑上使用同样的输入法，但这个问题如果无法解决我只能在手机上改回iPhone内建的最普通的小鹤双拼了(就会没有辅助码功能)。

我如果用别的输入法比如雾凇，它的*.schema.yaml档里面就有放switches的段落。
虽然我是程式小白，但经过许多查询我也知道可以改：

switches:
  - name: traditionalization
    states: [ 简, 繁 ]
    reset: 1

就可以在仓输入法里面变成预设繁体了。

但是在moqi_wan_flypymo.schema.yaml档案里面，找不到switches的段落，所以即使我会上面的方式能在ios仓输入法上把雾凇的switches改成预设繁体输出(我也只会这招)，我也找不到方式把墨奇在ios仓输入法上改成预设繁体输出。

这个问题对我真的很重要，希望有解，请大家帮帮我，感谢了。

**Comment by gaboolic** [comment, marked as answer]
在moqi.yaml里面  一样的
```
switches_engine:  
  switches:
    - name: ascii_mode
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: traditionalization
      states: [ 简, 繁 ]
    - name: emoji
      states: [ 💀, 😄 ]
    - name: chaifen
      states: [ 不拆, 扌斥 ]
    - name: big_char_set
      states: [ 大字集, 小字集 ]
    - name: mars
      reset: 0
      states: [ 地, 煋 ] #火星文
    - name: ascii_punct
      states: [ 。，, ．， ]
```
